- .github/workflows/main.yml
- composer.json
- Part One of https://github.com/phenaproxima/drupal-suite/issues/1
---
- Per discussion with you, macOS and Windows support have been deferred to an as-yet unprioritized follow-up issue.
- I configured it to run on pushes and pull requests, even though that wasn't explicitly in the requirements, because it seemed obvious and I assume you would want it.
- This doesn't install Nightwatch or any supplementary testing requirements, as they weren't in the success criteria. Obviously, they can be added in follow-ups as necessary.
- ~I assume that Apache is multi-threaded by default, but I haven't confirmed it. I don't know, for example, if it has to have [the MPM worker](https://httpd.apache.org/docs/2.4/mod/worker.html) specifically enabled. Unless you know the answer, I'll check on it (or it …
> Set up a GitHub Actions workflow

- composer.json
@phenaproxima what would you think of breaking `drupal quick-start` into a separate Composer script so it can be easily run again at any time on an existing installation?
```
$ composer | grep drupal:quick-start
drupal:quick-start   [qs] Installs Drupal CMS (if not already installed) and runs the PHP webserver.
$  starshot-project (feature/separate-quick-start-script $=) composer run
Script to run:
[drupal:install         ] Installs Drupal CMS.
[drupal:install-dev     ] Installs Drupal CMS, with additional modules and configuration tweaks for development.
[drupal:quick-start     ] Installs Drupal CMS (if not already installed) and runs the PHP webserver.
[post-create-project-cmd]
$ composer drupal:quick-start
> Composer\Config::disableProcessTimeout
> @php web/core/scripts/drupal …
```
> Separate drupal:quick-start into its own Composer script

- .tugboat/config.yml
This gets us started with the ability to manually spin up Tugboat previews on-demand. We can iterate from here with PRs and schedules.
> Add basic Tugboat configuration

- composer.json
What would you think of this, @phenaproxima? This completely resets the application by removing all Composer artifacts (`vendor/`, `web/`, and `composer.lock`), reinstalling them with `composer install`, and running the Starshot install scripts. It's particularly helpful after a `git pull`.
> Add a `drupal:rebuild` Composer script

- .github/workflows/main.yml
- tests/src/ExistingSite/BasicExpectationsTest.php
- tests/src/ExistingSite/MetaTagsTest.php
We had some trouble with meta tags not appearing, so let's let our first real test coverage be proving that all content types actually have meta tags that show up.
> Add test coverage of meta tags configuration

- drush/drush.yml
A lot folks would doubtless be helped if Drush was pre-configured to use a URI of `http://localhost/` instead of `http://default/` .
> Add default `uri` option to `drush/drush.yml`

- .github/workflows/main.yml
- .gitignore
- composer.json
If we want to encourage contribution, we should make it as simple as possible. This provides a `composer drupal:run-tests` (`composer test`) script to run PHPUnit.
> Add `drupal:run-tests` Composer script

- README.md
Add a section to the README detailing the server timeout issue experienced by some users and the recommended command (`composer drupal:run-server`) to restart the server and mitigate the problem. This update provides clarity and support for developers encountering this issue.
> docs: :memo: Document workaround for server timeout issue in README

- recipes/starshot/config/metatag.metatag_defaults.front.yml
- tests/src/ExistingSite/MetaTagsTest.php
The front page title is currently "| Drupal" (by reason of whatever train of default values). Why don't we just set it to "Drupal" (`[site:name]`), so it looks finished.
> Set the front page title

- recipes/starshot/recipe.yml
I left the `verify_mail: true` setting even though it's not required, because it's a useful default if you do end up enabling registration. But I could see an argument for removing it.
> Update registration to admin only

- .ddev/commands/host/install
- .github/workflows/ddev.yml
Following up #50. We should really confirm continuously that Starshot works with DDEV.
> Add a CI workflow to confirm that Starshot can be spun up with DDEV.

- .ddev/commands/host/install
- .ddev/config.yaml
- .ddev/mutagen/mutagen.yml
- composer.json
- drush/drush.yml
This PR allows DDEV, if used, to manage the site settings and run the database container, so that Drupal installs into the database provided by DDEV, rather than forcing a SQLite database.
It preserves the existing behavior of `composer create-project`, installing into a SQLite database via Drush.
> Make it possible to install into a different, non-SQLite database

- composer.json
- installer/composer.json
- recipes/starshot/composer.json
- recipes/starshot_admin_theme/composer.json
- recipes/starshot_audio_media_type/composer.json
- recipes/starshot_basic_html_editor/composer.json
- recipes/starshot_blog/composer.json
- recipes/starshot_content_type_base/composer.json
- recipes/starshot_document_media_type/composer.json
- recipes/starshot_event_content_type/composer.json
- recipes/starshot_forms/composer.json
- recipes/starshot_full_html_editor/composer.json
- recipes/starshot_image_media_type/composer.json
- recipes/starshot_local_video_media_type/composer.json
- recipes/starshot_page_content_type/composer.json
This is mostly just to provide an example of how recipes should be distributed in the wild, but if any of these get split out into the final Starshot product, it'll still be helpful.
> Give all component recipes their own composer.json files

- .ddev/config.yaml
- composer.json
Since we now always install dependencies via `composer create-project`, it is possible for DDEV and the host machine to have dependency conflicts due to different PHP platform versions.
To get around this, it's best for us to explicitly tell Composer which PHP version it should consider when resolving dependencies. Let's make that PHP 8.1, which is the minimum version required by Drupal 10.
> Make Composer resolve dependencies from the PHP 8.1 platform

- composer.json
composer/installers 2.3 has been released with native support for the `drupal-recipe` package type, so we don't need `oomphinc/composer-installers-extender` anymore!
> Remove oomphinc/composer-installers-extender

- .ddev/example.config.local.yaml
Let's help out DDEV users get started with local configuration overrides. See https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#extending-configyaml-with-custom-configyaml-files.
> Add an example local DDEV config override file

- .ddev/config.yaml
Normally `router_http_port` and `router_https_port` should not be set in the project; they should be set globally. Having them here would override what might be set globally.
> Remove router_http_port from project .ddev/config.yaml

- README.md
* #137 
Remove the scary warning and don't have people do weird things with their Docker Desktop mounting strategy.
> docs: remove README section about database disk image malformed, fixes #137

- .ddev/config.yaml
I happened to note that this has the unnecessary 
```
web_environment:
- DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL
```
DDEV already provides DRUSH_OPTIONS_URL for all `drupal*` project types. 
This PR removes it. It's not doing any harm, but not doing any good either.
> Remove DRUSH_OPTIONS_URI as unnecessary (DDEV provides it already)

- .ddev/commands/host/quick-start
- .github/workflows/ddev.yml
* ddev quick-start is set up to not fail when one of its component scripts, like drush site-install fails
* This change addresses this by forcing an error code on the quick-start script when of of its components fail
I'm not sure whether this is by design and I understand the main.yml script also checks the site-install process, I just thought it was weird this script will not fail when the installation process has errors.
> Update ddev.yml to fail when quickstart fails

- composer.json
- installer/starshot_installer.profile
- patches/core/recipes-150.patch
- recipes/starshot_event_content_type/config/geocoder.geocoder_provider.nominatim.yml
- recipes/starshot_event_content_type/recipe.yml
Part of why Starshot needs an install profile is to run a function that configures the Nominatim geocoder with a user agent and referer.
Once https://www.drupal.org/project/distributions_recipes/issues/3303126 lands, recipes will have the ability to use existing config values as ephemeral tokens, thus obviating the need for that function. Why wait, though? We can patch core. I propose we do just that, with an abbreviated patch from that issue (we don't need the tests), and trim the install profile down a bit. This brings us a step closer to being able to install Starshot at the command line without using the profile at all.
> Use recipes' ability to borrow values from existing config to set up the Nominatim geocoder

- recipes/starshot/recipe.yml
The accessibility of Drupal forms can be improved by enabling the Inline form errors module.
https://www.drupal.org/docs/8/core/modules/inline-form-errors
Install the core inline form errors module.
> Enabling Inline form errors module to improve form a11y.

- recipes/starshot_admin_theme/recipe.yml
The accessibility of the gin admin theme can be improved by enabling its high contrast option.
Enable the high contrast mode.
> Enable Gin's high contrast mode to improve accessibility

- recipes/starshot_admin_theme/composer.json
- recipes/starshot_admin_theme/recipe.yml
- recipes/starshot_content_type_base/composer.json
- recipes/starshot_content_type_base/recipe.yml
I think these modules are distinct improvements the admin experience and not really part of the content types' data models or features. Therefore, let's move them to the starshot_admin_theme recipe.
> Move Simple Add More and Type Tray into the starshot_admin_theme recipe

- composer.json
- installer/starshot_installer.profile
- patches/core/core-recipes-user-import.patch
- recipes/starshot_anti_spam/recipe.yml
- recipes/starshot_basic_html_editor/recipe.yml
This changes the installer in such a way that we don't need to add additional steps; we can just piggyback on existing installer tasks.
> Clean up the installer by wrapping existing install tasks

- README.md
- recipes/starshot/composer.json
- recipes/starshot/recipe.yml
Logging in by username only is outmoded and inconvenient. Let's make it possible to login with your email address. I haven't personally used this module before but it has a solid install base and claims to be zero configuration.
I'll leave the final decision to commit to @pameeela or someone else who actually builds sites, but from a value perspective, in my personal opinion, this feels like the no-braineriest of no-brainers.
> Add login_emailusername
